[package]
name = "graphplan"
version = "0.1.0"
authors = ["Alex Kehayias <alex.kehayias@gmail.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "plangraph"
harness = false