initial = [
  "rocket1_location1",
  "rocket2_location2",
]

goals = [
  "rocket1_location3",
  "rocket2_location3",
]

actions = [
  { name = "move_rocket1_location2", reqs = ["rocket1_location1"], effects = ["rocket1_location2"] },
  { name = "move_rocket1_location3", reqs = ["rocket1_location2"], effects = ["rocket1_location3"] },
  { name = "move_rocket2_location3", reqs = ["rocket2_location2"], effects = ["rocket2_location3"] }
]